VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('08')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 4
MINOR_VERSION = 17
PATCH_VERSION = 202401081716
version_date = '2024/01/08 17:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
