VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('07')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202109071526
version_date = '2021/09/07 15:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
